/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { SummaryRequest } from "./SummaryRequest";
import { SummaryRequestCountArgs } from "./SummaryRequestCountArgs";
import { SummaryRequestFindManyArgs } from "./SummaryRequestFindManyArgs";
import { SummaryRequestFindUniqueArgs } from "./SummaryRequestFindUniqueArgs";
import { DeleteSummaryRequestArgs } from "./DeleteSummaryRequestArgs";
import { SummaryRequestService } from "../summaryRequest.service";
@graphql.Resolver(() => SummaryRequest)
export class SummaryRequestResolverBase {
  constructor(protected readonly service: SummaryRequestService) {}

  async _summaryRequestsMeta(
    @graphql.Args() args: SummaryRequestCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [SummaryRequest])
  async summaryRequests(
    @graphql.Args() args: SummaryRequestFindManyArgs
  ): Promise<SummaryRequest[]> {
    return this.service.summaryRequests(args);
  }

  @graphql.Query(() => SummaryRequest, { nullable: true })
  async summaryRequest(
    @graphql.Args() args: SummaryRequestFindUniqueArgs
  ): Promise<SummaryRequest | null> {
    const result = await this.service.summaryRequest(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SummaryRequest)
  async deleteSummaryRequest(
    @graphql.Args() args: DeleteSummaryRequestArgs
  ): Promise<SummaryRequest | null> {
    try {
      return await this.service.deleteSummaryRequest(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
